[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[[bin]]
name = "{{ project_name }}"
path = "./src/bin/main.rs"
#%if option("embedded-test")
test = false

[[test]]
name    = "hello_test"
harness = false

[lib]
test = false
#%endif

[dependencies]
esp-hal = { version = "~1.0", features = [
    "{{ chip.name }}",
    #%if option("unstable-hal")
    "unstable",
    #%endif
    #%if option("defmt")
    #+"defmt",
    #%endif
    #%if option("log")
    "log-04",
    #%endif
] }

#%if option("embassy") || option("wifi") || option("ble-bleps") || option("ble-trouble")
esp-rtos = { version = "0.2.0", features = [
    #%if option("wifi") || option("ble-bleps") || option("ble-trouble")
    "esp-radio",
    #%endif
    #%if option("alloc")
    "esp-alloc",
    #%endif
    #%if option("embassy")
    "embassy",
    #%endif
    "{{ chip.name }}",
    #%if option("defmt")
    #+"defmt",
    #%endif
    #%if option("log")
    "log-04",
    #%endif
]}
#%endif

esp-bootloader-esp-idf = { version = "0.4.0", features = [
    #%if option("defmt")
    #+"defmt",
    #%endif
    #%if option("log")
    "log-04",
    #%endif
    "{{ chip.name }}",
] }
#%if option("defmt")
#+defmt = "1.0.1"
#%else if option("log")
log = "0.4.27"
#%endif

#%if group_selected("log-frontend") || group_selected("panic-handler") || option("probe-rs")
#%if option("probe-rs")
#%if option("defmt")
rtt-target = { version = "0.6.2", features = ["defmt"] }
#%else
#+rtt-target = "0.6.2"
#%endif defmt
#%else
esp-println = { version = "0.16.1", features = [
    "{{ chip.name }}",
    #%if option("defmt")
    #+"defmt-espflash",
    #%endif
    #%if option("log")
    "log-04",
    #%endif
] }
#%endif probe-rs
#%endif log-frontend || panic-handler || probe-rs
#%if option("esp-backtrace")
esp-backtrace = { version = "0.18.1", features = [
    "{{ chip.name }}",
    "panic-handler",
    #%if option("defmt")
    #+"defmt",
    #%else
    "println",
    #%endif
] }
#%else if option("panic-rtt-target")
#%if option("defmt")
#+panic-rtt-target = { version = "0.2.0", features = ["defmt"] }
#%else
panic-rtt-target = "0.2.0"
#%endif defmt
#%endif esp-backtrace
#%if option("alloc")
#%if option("defmt")
#+esp-alloc = { version = "0.9.0", features = ["defmt"] }
#%else
esp-alloc = "0.9.0"
#%endif defmt
#%endif alloc
#%if option("wifi") || option("ble-bleps") || option("ble-trouble")
#%if option("defmt")
#+embedded-io = { version = "0.7.1", features = ["defmt"] }
#%else
embedded-io = "0.7.1"
#%endif defmt
#%if option("embassy")
#%if option("defmt")
#+embedded-io-async = { version = "0.7.0", features = ["defmt"] }
#%else
embedded-io-async = "0.7.0"
#%endif defmt
#%if option("wifi")
embassy-net = { version = "0.7.1", features = [
    "tcp",
    "udp",
    "dhcpv4",
    "medium-ethernet",
    #%if option("defmt")
    #+"defmt",
    #%endif
    #%if option("log")
    "log",
    #%endif
] }
# for more networking protocol support see https://crates.io/crates/edge-net
#%endif wifi
#%endif embassy
#%if option("wifi")
smoltcp = { version = "0.12.0", default-features = false, features = [
    "medium-ethernet",
    "multicast",
    "proto-dhcpv4",
    "proto-dns",
    "proto-ipv4",
    "socket-dns",
    "socket-raw",
    "socket-tcp",
    "socket-udp",
    "socket-icmp",
    #%if option("defmt")
    #+"defmt",
    #%endif
    #%if option("log")
    "log",
    #%endif
] }
#%endif wifi
esp-radio = { version = "0.17.0", features = [
    "{{ chip.name }}",
    #%if option("wifi")
    "wifi",
    "smoltcp",
    #%endif
    #%if option("ble-bleps") || option("ble-trouble")
    "ble",
    #%endif
    #%if option("wifi") && (option("ble-bleps") || option("ble-trouble"))
    "coex",
    #%endif
    #%if option("alloc")
    "esp-alloc",
    #%endif
    "unstable",
    #%if option("defmt")
    #+"defmt",
    #%endif
    #%if option("log")
    "log-04",
    #%endif
] }
#%if option("ble-bleps")
#+bleps = { git = "https://github.com/bjoernQ/bleps", package = "bleps", rev = "a5148d8ae679e021b78f53fd33afb8bb35d0b62e", features = [ "macros", "async"] }
#%endif
#%if option("ble-trouble")
#+trouble-host = { version = "0.5.0", features = ["gatt"] }
#+bt-hci = "0.6.0"
#%endif
#%endif wifi || ble || ble-trouble
#%if option("embassy")
embassy-executor = { version = "0.9.1", features = [
    #%if option("defmt")
    #+"defmt",
    #%endif
    #%if option("log")
    "log",
    #%endif
] }
#%if option("defmt")
#+embassy-time     = { version = "0.5.0", features = ["defmt"] }
#%endif
#%if option("log")
embassy-time = { version = "0.5.0", features = ["log"] }
#%endif
#%if !option("defmt") && !option("log")
#+embassy-time     = "0.5.0"
#%endif

static_cell = "2.1.1"
#%endif
critical-section = "1.2.0"

#%if option("display")
embedded-graphics = "0.8"
mipidsi = "0.7"
display-interface = "0.4"
embedded-graphics-framebuf = "0.5"
embedded-hal = "1.0"
heapless = { version = "0.8.0", default-features = false }
#%endif

#%if option("touch") || option("imu")
#%if option("display")
embedded-hal-bus = "0.2"
#%endif
#%if option("touch")
axs5106l = "0.1"
#%endif
#%if option("imu")
ph-qmi8658 = "0.1"
#%endif
#%endif

#%if option("embedded-test")
[dev-dependencies]
embedded-test = { version = "0.7.0", features = [
    #%if chip.xtensa
    "xtensa-semihosting",
    #%endif
    #%if option("embassy")
    "embassy",
    "external-executor",
    #%endif
    #%if option("defmt")
    #+"defmt",
    #%endif
    #%if option("log")
    "log-04",
    #%endif
] }
#%endif embedded-test

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1       # LLVM can perform better optimizations using a single thread
debug = 2               # prefer slower builds but better debugging experience
lto = 'fat'
opt-level = 's'
